CREATE TABLE `intake_form_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sectionKey` varchar(100) NOT NULL,
	`sectionNumber` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`displayText` text,
	`isRequired` boolean NOT NULL DEFAULT true,
	`requiresSignature` boolean NOT NULL DEFAULT false,
	`requiresCheckbox` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intake_form_config_id` PRIMARY KEY(`id`),
	CONSTRAINT `intake_form_config_sectionKey_unique` UNIQUE(`sectionKey`)
);
--> statement-breakpoint
CREATE TABLE `intake_form_responses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`enrollmentId` int NOT NULL,
	`userId` int,
	`status` enum('in_progress','completed','needs_review') NOT NULL DEFAULT 'in_progress',
	`currentSection` int NOT NULL DEFAULT 1,
	`completedSections` text,
	`fullName` varchar(255),
	`dateOfBirth` date,
	`sex` enum('female','male','intersex','prefer_not_to_say'),
	`email` varchar(320),
	`phone` varchar(50),
	`streetAddress` text,
	`city` varchar(255),
	`stateProvince` varchar(100),
	`country` varchar(100) DEFAULT 'United States',
	`zipCode` varchar(20),
	`height` varchar(50),
	`currentWeight` varchar(50),
	`goalWeight` varchar(50),
	`bodyFatPercentage` varchar(50),
	`peptideGoals` text,
	`primaryGoal` text,
	`secondaryGoal` text,
	`additionalGoals` text,
	`previousPeptideExperience` text,
	`foodCravings` text,
	`currentSupplements` text,
	`medicalIssues` text,
	`physicalActivityRoutine` text,
	`physicalLimitations` text,
	`hormonalStatus` text,
	`currentMedications` text,
	`foodIntolerances` text,
	`digestiveIssues` text,
	`medicalDiagnoses` text,
	`otherGoalSupport` text,
	`aggressivenessScale` int,
	`financialAggressivenessScale` int,
	`organizationalCapacityScale` int,
	`otherConcerns` text,
	`additionalContext` text,
	`referralSource` varchar(255),
	`referralName` varchar(255),
	`referralOther` varchar(255),
	`safetyScreenFlags` text,
	`mentalHealthHistory` text,
	`psychMedications` text,
	`emergencyContactName` varchar(255),
	`emergencyContactRelationship` varchar(100),
	`emergencyContactPhone` varchar(50),
	`alcoholUse` text,
	`nicotineUse` text,
	`cannabisUse` text,
	`otherSubstanceUse` text,
	`sleepDuration` varchar(50),
	`sleepQuality` int,
	`stressLevel` int,
	`mainStressors` text,
	`stressManagementMethods` text,
	`wearableDevices` text,
	`typicalMetricsTracked` text,
	`top3Goals` text,
	`weeklyTimeCommitment` varchar(100),
	`isMinor` boolean NOT NULL DEFAULT false,
	`parentGuardianName` varchar(255),
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`lastSavedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`submittedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `intake_form_responses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `intake_form_signatures` (
	`id` int AUTO_INCREMENT NOT NULL,
	`intakeFormId` int NOT NULL,
	`enrollmentId` int NOT NULL,
	`sectionKey` varchar(100) NOT NULL,
	`signatureType` enum('drawn','typed') NOT NULL,
	`signatureData` text NOT NULL,
	`signedName` varchar(255),
	`ipAddress` varchar(45),
	`userAgent` text,
	`signedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `intake_form_signatures_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE INDEX `intake_config_section_key_idx` ON `intake_form_config` (`sectionKey`);--> statement-breakpoint
CREATE INDEX `intake_config_sort_idx` ON `intake_form_config` (`sortOrder`);--> statement-breakpoint
CREATE INDEX `intake_response_enrollment_idx` ON `intake_form_responses` (`enrollmentId`);--> statement-breakpoint
CREATE INDEX `intake_response_user_idx` ON `intake_form_responses` (`userId`);--> statement-breakpoint
CREATE INDEX `intake_response_status_idx` ON `intake_form_responses` (`status`);--> statement-breakpoint
CREATE INDEX `intake_sig_form_idx` ON `intake_form_signatures` (`intakeFormId`);--> statement-breakpoint
CREATE INDEX `intake_sig_enrollment_idx` ON `intake_form_signatures` (`enrollmentId`);--> statement-breakpoint
CREATE INDEX `intake_sig_section_idx` ON `intake_form_signatures` (`sectionKey`);