-- Test-DB schema — `client_protocols`. Extracted from the prod snapshot, TiDB comments stripped.
-- Regenerate: see test-harness/README.md (Extending the schema).

CREATE TABLE `client_protocols` (
  `id` int NOT NULL AUTO_INCREMENT,
  `clientName` varchar(255) NOT NULL,
  `clientEmail` varchar(320) DEFAULT NULL,
  `clientPhone` varchar(50) DEFAULT NULL,
  `accessToken` varchar(64) NOT NULL,
  `templateId` int DEFAULT NULL,
  `durationMonths` int NOT NULL DEFAULT '3',
  `status` enum('draft','pending_approval','approved','active','completed') NOT NULL DEFAULT 'draft',
  `approvedAt` timestamp NULL DEFAULT NULL,
  `discountPercent` decimal(5,2) DEFAULT '0',
  `coachingPackage` varchar(255) DEFAULT NULL,
  `coachingPrice` decimal(10,2) DEFAULT '0',
  `paymentMethod` enum('venmo','cc','other','paypal') DEFAULT 'venmo',
  `venmoHandle` varchar(100) DEFAULT NULL,
  `customRequirements` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `firstViewedAt` timestamp NULL DEFAULT NULL,
  `archivedAt` timestamp NULL DEFAULT NULL,
  `deletedAt` timestamp NULL DEFAULT NULL,
  `programId` int DEFAULT NULL,
  `currentPhaseId` int DEFAULT NULL,
  `phaseStartDate` timestamp NULL DEFAULT NULL,
  `programStartDate` timestamp NULL DEFAULT NULL,
  `coachNotes` text DEFAULT NULL,
  `sentAt` timestamp NULL DEFAULT NULL,
  `shippingName` varchar(255) DEFAULT NULL,
  `shippingStreet` varchar(500) DEFAULT NULL,
  `shippingCity` varchar(255) DEFAULT NULL,
  `shippingState` varchar(100) DEFAULT NULL,
  `shippingZip` varchar(20) DEFAULT NULL,
  `shippingCountry` varchar(100) DEFAULT NULL,
  `shippingPhone` varchar(50) DEFAULT NULL,
  `onboardingCompletedAt` timestamp NULL DEFAULT NULL,
  `onboardingPath` varchar(50) DEFAULT NULL,
  `onboardingSelection` varchar(100) DEFAULT NULL,
  `lastFollowUpSentAt` timestamp NULL DEFAULT NULL,
  `followUpCount` int NOT NULL DEFAULT '0',
  `internalNotes` text DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `paymentStatus` enum('pending','paid','failed','refunded') DEFAULT 'pending',
  `paymentReceivedAt` timestamp NULL DEFAULT NULL,
  `showAffiliateLinks` tinyint(1) NOT NULL DEFAULT '1',
  `inviteSentAt` timestamp NULL DEFAULT NULL,
  `paymentReminderOptOut` tinyint(1) NOT NULL DEFAULT '0',
  `clientId` int DEFAULT NULL,
  `version` int NOT NULL DEFAULT '1',
  `versionName` varchar(100) DEFAULT NULL,
  `isActiveVersion` tinyint(1) NOT NULL DEFAULT '1',
  `previousVersionId` int DEFAULT NULL,
  `completedAt` timestamp NULL DEFAULT NULL,
  `versionNotes` text DEFAULT NULL,
  `clientVisibility` enum('hidden','option','active','archived') NOT NULL DEFAULT 'active',
  `engagementLevel` enum('full_coaching','self_guided_checkins','protocol_only') NOT NULL DEFAULT 'protocol_only',
  `lastViewedAt` timestamp NULL DEFAULT NULL,
  `viewCount` int NOT NULL DEFAULT '0',
  `renewedFromId` int DEFAULT NULL,
  `startDate` timestamp NULL DEFAULT NULL,
  `endDate` timestamp NULL DEFAULT NULL,
  `inventoryDeductedAt` timestamp NULL DEFAULT NULL,
  `contactId` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `client_protocols_accessToken_unique` (`accessToken`),
  KEY `client_protocols_email_idx` (`clientEmail`),
  KEY `client_protocols_status_idx` (`status`),
  KEY `client_protocols_template_idx` (`templateId`),
  KEY `client_protocols_program_idx` (`programId`),
  KEY `client_protocols_client_id_idx` (`clientId`),
  KEY `client_protocols_client_active_idx` (`clientId`,`isActiveVersion`),
  KEY `client_protocols_contact_idx` (`contactId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=2190001;
