-- Test-DB schema — `transformation_enrollments`. Extracted from the prod snapshot, TiDB comments stripped.
-- Regenerate: see test-harness/README.md (Extending the schema).

CREATE TABLE `transformation_enrollments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `userId` int DEFAULT NULL,
  `clientId` int DEFAULT NULL,
  `accessCodeId` int DEFAULT NULL,
  `programType` enum('90_day_transformation','protocol_only') NOT NULL DEFAULT '90_day_transformation',
  `status` enum('enrolled','watching_videos','video_complete','coaching_paid','intake_complete','discovery_scheduled','discovery_complete','protocol_preparing','protocol_review','protocol_paid','launched','fulfillment','shipped','delivered','training_scheduled','training_complete','active','week3_review','month2','month3_final','completed','renewed') NOT NULL DEFAULT 'enrolled',
  `coachingFeePaid` tinyint(1) NOT NULL DEFAULT '0',
  `coachingFeeAmount` decimal(10,2) DEFAULT NULL,
  `coachingFeePaidAt` timestamp NULL DEFAULT NULL,
  `coachingFeeStripePaymentId` varchar(255) DEFAULT NULL,
  `protocolCostPaid` tinyint(1) NOT NULL DEFAULT '0',
  `protocolCostAmount` decimal(10,2) DEFAULT NULL,
  `protocolCostPaidAt` timestamp NULL DEFAULT NULL,
  `protocolCostStripePaymentId` varchar(255) DEFAULT NULL,
  `clientProtocolId` int DEFAULT NULL,
  `discoverySessionScheduledAt` timestamp NULL DEFAULT NULL,
  `discoverySessionCompletedAt` timestamp NULL DEFAULT NULL,
  `reconstitutionSessionScheduledAt` timestamp NULL DEFAULT NULL,
  `reconstitutionSessionCompletedAt` timestamp NULL DEFAULT NULL,
  `week3ReviewScheduledAt` timestamp NULL DEFAULT NULL,
  `week3ReviewCompletedAt` timestamp NULL DEFAULT NULL,
  `month2SessionScheduledAt` timestamp NULL DEFAULT NULL,
  `month2SessionCompletedAt` timestamp NULL DEFAULT NULL,
  `finalReviewScheduledAt` timestamp NULL DEFAULT NULL,
  `finalReviewCompletedAt` timestamp NULL DEFAULT NULL,
  `boxShippedAt` timestamp NULL DEFAULT NULL,
  `boxDeliveredAt` timestamp NULL DEFAULT NULL,
  `trackingNumber` varchar(255) DEFAULT NULL,
  `omegaEliteActivatedAt` timestamp NULL DEFAULT NULL,
  `omegaEliteExpiresAt` timestamp NULL DEFAULT NULL,
  `biologicalAgeTestOrdered` tinyint(1) NOT NULL DEFAULT '0',
  `biologicalAgeTestOrderedAt` timestamp NULL DEFAULT NULL,
  `biologicalAgeResult` decimal(5,2) DEFAULT NULL,
  `biologicalAgeResultAt` timestamp NULL DEFAULT NULL,
  `coachNotes` text DEFAULT NULL,
  `enrolledAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `launchedAt` timestamp NULL DEFAULT NULL,
  `completedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tier` enum('elite','flagship','essentials','advanced','recovery','immunity','longevity','mitochondria','functional_health_elite') NOT NULL DEFAULT 'flagship',
  `intakeFormCompleted` tinyint(1) NOT NULL DEFAULT '0',
  `intakeFormCompletedAt` timestamp NULL DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `clientName` varchar(255) DEFAULT NULL,
  `authToken` varchar(255) DEFAULT NULL,
  `authTokenExpiresAt` timestamp NULL DEFAULT NULL,
  `followUpReminderSentAt` timestamp NULL DEFAULT NULL,
  `stalledNotificationSentAt` datetime DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `shippingName` varchar(255) DEFAULT NULL,
  `shippingStreet` varchar(500) DEFAULT NULL,
  `shippingCity` varchar(255) DEFAULT NULL,
  `shippingState` varchar(100) DEFAULT NULL,
  `shippingZip` varchar(20) DEFAULT NULL,
  `shippingCountry` varchar(100) DEFAULT 'United States',
  `profileCompleted` tinyint(1) DEFAULT '0',
  `profileCompletedAt` datetime DEFAULT NULL,
  `intakeReminder24hSentAt` datetime DEFAULT NULL,
  `intakeReminder72hSentAt` datetime DEFAULT NULL,
  `contactId` int DEFAULT NULL,
  `vipConcierge` tinyint NOT NULL DEFAULT '0',
  `vipConciergeFee` decimal(10,2) DEFAULT NULL,
  `paymentPlanRequested` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `transformation_enroll_user_idx` (`userId`),
  KEY `transformation_enroll_client_idx` (`clientId`),
  KEY `transformation_enroll_status_idx` (`status`),
  KEY `transformation_enroll_protocol_idx` (`clientProtocolId`),
  KEY `transformation_enrollments_contact_idx` (`contactId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=1170001;
