-- Test-DB schema — `prospects`. Extracted from the prod snapshot, TiDB comments stripped.

CREATE TABLE `prospects` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(50) NOT NULL,
  `status` enum('new','contacted','clicked','viewing','enrolled','declined','stalled','engaged','waiting_on_client','ready_for_consult','not_ready') NOT NULL DEFAULT 'new',
  `source` varchar(100) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `accessCode` varchar(100) DEFAULT NULL,
  `trackingToken` varchar(100) NOT NULL,
  `lastContactedAt` timestamp NULL DEFAULT NULL,
  `lastClickedAt` timestamp NULL DEFAULT NULL,
  `lastViewedAt` timestamp NULL DEFAULT NULL,
  `totalSmsSent` int NOT NULL DEFAULT '0',
  `totalClicks` int NOT NULL DEFAULT '0',
  `followUpCount` int NOT NULL DEFAULT '0',
  `nextFollowUpAt` timestamp NULL DEFAULT NULL,
  `followUpPaused` tinyint(1) NOT NULL DEFAULT '0',
  `enrollmentId` int DEFAULT NULL,
  `userId` int DEFAULT NULL,
  `clientId` int DEFAULT NULL,
  `smsOptOut` tinyint(1) NOT NULL DEFAULT '0',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `customStatus` varchar(100) DEFAULT NULL,
  `thingsToKnow` text DEFAULT NULL,
  `assignedTo` int DEFAULT NULL,
  `contactId` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `prospects_status_idx` (`status`),
  KEY `prospects_email_idx` (`email`),
  KEY `prospects_phone_idx` (`phone`),
  KEY `prospects_tracking_token_idx` (`trackingToken`),
  KEY `prospects_next_followup_idx` (`nextFollowUpAt`),
  KEY `prospects_contact_idx` (`contactId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=720001;
