-- Test-DB schema — `intake_form_responses`. Extracted from the prod snapshot, TiDB comments stripped.
-- Added 2026-07-29 to runtime-verify the intake-form and check-in authorization gates,
-- which could not be exercised against the previous 10-table harness.
-- Regenerate: see test-harness/README.md (Extending the schema).

CREATE TABLE `intake_form_responses` (
  `id` int NOT NULL AUTO_INCREMENT,
  `enrollmentId` int NOT NULL,
  `userId` int DEFAULT NULL,
  `status` enum('in_progress','completed','needs_review') NOT NULL DEFAULT 'in_progress',
  `currentSection` int NOT NULL DEFAULT '1',
  `completedSections` text DEFAULT NULL,
  `fullName` varchar(255) DEFAULT NULL,
  `dateOfBirth` date DEFAULT NULL,
  `sex` enum('female','male','intersex','prefer_not_to_say') DEFAULT NULL,
  `email` varchar(320) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `streetAddress` text DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `stateProvince` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT 'United States',
  `zipCode` varchar(20) DEFAULT NULL,
  `height` varchar(50) DEFAULT NULL,
  `currentWeight` varchar(50) DEFAULT NULL,
  `goalWeight` varchar(50) DEFAULT NULL,
  `bodyFatPercentage` varchar(50) DEFAULT NULL,
  `peptideGoals` text DEFAULT NULL,
  `primaryGoal` text DEFAULT NULL,
  `secondaryGoal` text DEFAULT NULL,
  `additionalGoals` text DEFAULT NULL,
  `previousPeptideExperience` text DEFAULT NULL,
  `foodCravings` text DEFAULT NULL,
  `currentSupplements` text DEFAULT NULL,
  `medicalIssues` text DEFAULT NULL,
  `physicalActivityRoutine` text DEFAULT NULL,
  `physicalLimitations` text DEFAULT NULL,
  `hormonalStatus` text DEFAULT NULL,
  `currentMedications` text DEFAULT NULL,
  `foodIntolerances` text DEFAULT NULL,
  `digestiveIssues` text DEFAULT NULL,
  `medicalDiagnoses` text DEFAULT NULL,
  `otherGoalSupport` text DEFAULT NULL,
  `aggressivenessScale` int DEFAULT NULL,
  `financialAggressivenessScale` int DEFAULT NULL,
  `organizationalCapacityScale` int DEFAULT NULL,
  `otherConcerns` text DEFAULT NULL,
  `additionalContext` text DEFAULT NULL,
  `referralSource` varchar(255) DEFAULT NULL,
  `referralName` varchar(255) DEFAULT NULL,
  `referralOther` varchar(255) DEFAULT NULL,
  `safetyScreenFlags` text DEFAULT NULL,
  `mentalHealthHistory` text DEFAULT NULL,
  `psychMedications` text DEFAULT NULL,
  `emergencyContactName` varchar(255) DEFAULT NULL,
  `emergencyContactRelationship` varchar(100) DEFAULT NULL,
  `emergencyContactPhone` varchar(50) DEFAULT NULL,
  `alcoholUse` text DEFAULT NULL,
  `nicotineUse` text DEFAULT NULL,
  `cannabisUse` text DEFAULT NULL,
  `otherSubstanceUse` text DEFAULT NULL,
  `sleepDuration` varchar(50) DEFAULT NULL,
  `sleepQuality` int DEFAULT NULL,
  `stressLevel` int DEFAULT NULL,
  `mainStressors` text DEFAULT NULL,
  `stressManagementMethods` text DEFAULT NULL,
  `wearableDevices` text DEFAULT NULL,
  `typicalMetricsTracked` text DEFAULT NULL,
  `top3Goals` text DEFAULT NULL,
  `weeklyTimeCommitment` varchar(100) DEFAULT NULL,
  `isMinor` tinyint(1) NOT NULL DEFAULT '0',
  `parentGuardianName` varchar(255) DEFAULT NULL,
  `startedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastSavedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `submittedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`) ,
  KEY `intake_response_enrollment_idx` (`enrollmentId`),
  KEY `intake_response_user_idx` (`userId`),
  KEY `intake_response_status_idx` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
